USE master
GO

IF  EXISTS (
	SELECT name 
		FROM sys.databases 
		WHERE name = N'DBQuanLy'
)
DROP DATABASE DBQuanLy
GO

CREATE DATABASE DBQuanLy
GO

USE DBQuanLy
GO

CREATE TABLE TAIKHOAN
(
	Username VARCHAR(30) PRIMARY KEY NOT NULL,
	Password VARCHAR(30) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	PhanQuyen NVARCHAR(30) NOT NULL,
)
GO

CREATE FUNCTION ID_LH()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MALH) FROM LIENHE) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MALH, 3)) FROM LIENHE
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'LH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'LH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE LIENHE
(
	MaLH VARCHAR(5) PRIMARY KEY CONSTRAINT MaLH DEFAULT DBO.ID_LH(),
	TenLH NVARCHAR(50) NOT NULL,
	DiaChiLH NVARCHAR(100) NOT NULL,
	SDT VARCHAR(20) NOT NULL,
)
GO

CREATE FUNCTION ID_PL()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaLoai) FROM PHANLOAI) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaLoai, 3)) FROM PHANLOAI
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'ML00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'ML0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE PHANLOAI
(
	MaLoai VARCHAR(5) PRIMARY KEY CONSTRAINT MaLoai DEFAULT DBO.ID_PL(),
	TenLoai NVARCHAR(50) NOT NULL,
)
GO

CREATE FUNCTION ID_NCC()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaNCC) FROM NHACUNGCAP) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaNCC, 2)) FROM NHACUNGCAP
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NCC0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NCC' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE NHACUNGCAP
(
	MaNCC VARCHAR(5) PRIMARY KEY CONSTRAINT MaNCC DEFAULT DBO.ID_NCC(),
	TenNCC NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	SDT VARCHAR(20) NOT NULL,
)
GO

CREATE FUNCTION ID_NL()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaNL) FROM NGUYENLIEU) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaNL, 3)) FROM NGUYENLIEU
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NL00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NL0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE NGUYENLIEU
(
	MaNL VARCHAR(5) PRIMARY KEY CONSTRAINT MaNL DEFAULT DBO.ID_NL(),
	TenNL NVARCHAR(100) NOT NULL,
	MaNCC VARCHAR(5) NOT NULL,
	FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP (MaNCC)
)
GO

CREATE FUNCTION ID_SP()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaSP) FROM SANPHAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaSP, 3)) FROM SANPHAM
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'SP00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'SP0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE SANPHAM
(
	MaSP VARCHAR(5) PRIMARY KEY CONSTRAINT MaSP DEFAULT DBO.ID_SP(),
	TenSP NVARCHAR(30) NOT NULL,
	GiaBan NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(100) NOT NULL,
	Anh NVARCHAR(100) NOT NULL,
	MaNL VARCHAR(5) NOT NULL,
	MaLoai VARCHAR(5) NOT NULL,
	FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU (MaNL),
	FOREIGN KEY (MaLoai) REFERENCES PHANLOAI (MaLoai),
)
GO

CREATE FUNCTION ID_KH()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaKH) FROM KHACHHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaKH, 3)) FROM KHACHHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE KHACHHANG
(
	MaKH VARCHAR(5) PRIMARY KEY CONSTRAINT MaKH DEFAULT DBO.ID_KH(),
	TenKH NVARCHAR(30) NOT NULL,
	NgaySinh DATETIME NOT NULL,
	Username VARCHAR(30) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(200) NOT NULL,
	DienThoai VARCHAR(20) NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES TAIKHOAN (USERNAME),
)
GO

CREATE FUNCTION ID_DH()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaDH) FROM DONHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaDH, 3)) FROM DONHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'DH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'DH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE DONHANG
(
	MaDH VARCHAR(5) PRIMARY KEY CONSTRAINT MaDH DEFAULT DBO.ID_DH(),
	ThanhTien decimal(18,0) NOT NULL,
	PhuongThucThanhToan VARCHAR(50) nOT NULL,
	ThanhToan VARCHAR(30) NOT NULL,
	DiaChiGiaoHang VARCHAR(50) NOT NULL,
	TinhTrangGiaoHang VARCHAR(50) NOT NULL,
	NgayDat datetime NOT NULL,
	NgayGiao datetime NOT NULL,
	MaKH VARCHAR(5) NOT NULL,
	GhiChu NVARCHAR(100) NOT NULL,
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG (MaKH),
)
GO

CREATE FUNCTION ID_GH()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaGH) FROM GIOHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaGH, 3)) FROM GIOHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'GH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'GH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE GIOHANG
(
	MaGH VARCHAR(5) PRIMARY KEY CONSTRAINT MaGH DEFAULT DBO.ID_GH(),
	MaDH VARCHAR(5) NOT NULL,
	FOREIGN KEY (MaDH) REFERENCES DONHANG (MaDH),
)
GO

CREATE FUNCTION ID_HD()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaHD) FROM CHITIETDONHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHD, 3)) FROM CHITIETDONHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HD00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HD0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE CHITIETDONHANG
(
	MaHD VARCHAR(5) PRIMARY KEY CONSTRAINT MaHD DEFAULT DBO.ID_HD(),
	MaGH VARCHAR(5),
	MaSP VARCHAR(5),
	SoLuong INT NOT NULL,
	DonGia decimal(18,0) NOT NULL,
	FOREIGN KEY (MaSP) REFERENCES SANPHAM (MaSP),
	FOREIGN KEY (MaGH) REFERENCES GIOHANG (MaGH),
)
GO

CREATE FUNCTION ID_NV()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF (SELECT COUNT(MaNV) FROM NHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaNV, 3)) FROM NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE NHANVIEN
(
	MaNV VARCHAR(5) PRIMARY KEY CONSTRAINT MaNV DEFAULT DBO.ID_NV(),
	TenNV NVARCHAR(30) NOT NULL,
	NgaySinh datetime NOT NULL,
	Username VARCHAR(30) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(200) NOT NULL,
	DienThoai NVARCHAR(20) NOT NULL,
	STK VARCHAR(50) NOT NULL,
	Luong decimal(18,0) NOT NULL,
	FOREIGN KEY (Username) REFERENCES TAIKHOAN (Username),
)
GO

--TAIKHOAN
--SELECT * FROM TAIKHOAN
--Admin
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('longvt','1',N'Vũ Thế Long', N'Admin')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('minhbd','1',N'Bùi Đình Minh', N'Admin')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('anhnh','1',N'Nuyễn Hoàng Anh', N'Admin')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('sangttt','1',N'Triệu Trung Tấn Sang', N'Admin')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('sondh','1',N'Đỗ Hồng Sơn', N'Admin')
GO
--Khach hang
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('kh1','1','Long', N'Khách hàng')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('kh2','1',N'Minh', N'Khách hàng')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('kh3','1',N'Anh', N'Khách hàng')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('kh4','1',N'Sang', N'Khách hàng')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('kh5','1',N'Sơn', N'Khách hàng')
GO
--Nhan vien
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('nv1','1',N'Vũ', N'Nhân viên')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('nv2','1',N'Bùi', N'Nhân viên')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('nv3','1',N'Nguyễn', N'Nhân viên')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('nv4','1',N'Triệu', N'Nhân viên')
GO
INSERT INTO TAIKHOAN(Username, Password, HoTen, PhanQuyen) VALUES('nv5','1',N'Đỗ', N'Nhân viên')
GO

--LIENHE
--SELECT * FROM LIENHE
INSERT INTO LIENHE(TenLH, DiaChiLH, SDT) VALUES(N'Quan tra sua Lamss',N'Ha Noi', 1234)
GO

--PHANLOAI
--SELECT * FROM PHANLOAI
INSERT INTO PHANLOAI(TenLoai) VALUES(N'Trà sữa')
GO
INSERT INTO PHANLOAI(TenLoai) VALUES(N'Trà')
GO
INSERT INTO PHANLOAI(TenLoai) VALUES(N'Cà phê')
GO
INSERT INTO PHANLOAI(TenLoai) VALUES(N'Đồ ăn vặt')
GO

--NHACUNGCAP
--SELECT * FROM NHACUNGCAP
INSERT INTO NHACUNGCAP(TenNCC, DiaChi, SDT) VALUES(N'DingTea', N'Hải Phòng', 123)
GO
INSERT INTO NHACUNGCAP(TenNCC, DiaChi, SDT) VALUES(N'Tea Group', N'Hà Nội', 123)
GO
INSERT INTO NHACUNGCAP(TenNCC, DiaChi, SDT) VALUES(N'Trung Nguyên Cà Phê', N'Dalak', 123)
GO
INSERT INTO NHACUNGCAP(TenNCC, DiaChi, SDT) VALUES(N'Hoa Ban Food', N'Sơn La', 123)
GO
INSERT INTO NHACUNGCAP(TenNCC, DiaChi, SDT) VALUES(N'Hướng dương Food', N'Hải Phòng', 123)
GO

--NGUYENLIEU
--SELECT * FROM NGUYENLIEU
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Gói Trà sữa','NCC01')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Gói Trà sữa chân châu','NCC01')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Gói Trà sữa chân châu đường đen','NCC01')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Trà đào túi lọc','NCC02')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Trà Chanh túi lọc','NCC02')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Trà Tắc túi lọc','NCC02')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Hộp cà phê đen','NCC03')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Hộp cà phê sữa','NCC03')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Hộp cà phê Chery','NCC03')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Gói Khô gà','NCC04')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Gói Khô mực','NCC04')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Gói Khô bò','NCC04')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Túi hướng dương','NCC05')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Túi hướng dương vỏ ngọt','NCC05')
GO
INSERT INTO NGUYENLIEU(TenNL, MaNCC) VALUES(N'Túi hướng dương vỏ mặn','NCC05')
GO


--SANPHAM
--SELECT * FROM SANPHAM
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Trà sữa','40000',N'Sản phẩm bán chạy', N'None', 'NL001','ML001')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Trà sữa chân châu','50000',N'Sản phẩm bán chạy', N'None', 'NL002','ML001')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Trà sữa chân châu đường đen','60000',N'Sản phẩm bán chạy', N'None', 'NL003','ML001')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Trà đào','40000',N'Sản phẩm bán chạy', N'None', 'NL004','ML002')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Trà chanh','50000',N'Sản phẩm bán chạy', N'None', 'NL005','ML002')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Trà tắc','60000',N'Sản phẩm ăn chạy', N'None', 'NL006','ML002')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Cà phê đen','40000',N'Sản phẩmbán chạy', N'None', 'NL007','ML003')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Cà phê sữa','50000',N'Sản phẩm bán chạy', N'None', 'NL008','ML003')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Cà phê Chery','60000',N'Sản phẩm bán chạy', N'None', 'NL009','ML003')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Khô gà','40000',N'Sản phẩm ăn kèm bán chạy', N'None', 'NL010','ML004')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Khô mực','50000',N'Sản phẩm ăn kèm bán chạy', N'None', 'NL011','ML004')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Khô bò','60000',N'Sản phẩm ăn kèm bán chạy', N'None', 'NL012','ML004')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Hướng dương','40000',N'Sản phẩm ăn kèm bán chạy', N'None', 'NL013','ML004')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Hướng dương vỏ ngọt','50000',N'Sản phẩm ăn kèm bán chạy', N'None', 'NL014','ML004')
GO
INSERT INTO SANPHAM(TenSP, GiaBan, MoTa, Anh, MaNL, MaLoai) VALUES (N'Hướng dương vỏ mặn','60000',N'Sản phẩm ăn kèm bán chạy', N'None', 'NL015','ML004')
GO

--KHACHHANG
--SELECT * FROM KHACHHANG
--SELECT * FROM TAIKHOAN WHERE PhanQuyen = N'Khách hàng'
INSERT INTO KHACHHANG(TenKH, NgaySinh, USERNAME, Email, DiaChi, DienThoai) VALUES (N'Long', '1/1/2022', 'kh1', 'long@gmail.com', N'Hà Nội', 0971)
GO
INSERT INTO KHACHHANG(TenKH, NgaySinh, USERNAME, Email, DiaChi, DienThoai) VALUES (N'Minh', '1/1/2022', 'kh2', 'minh@gmail.com', N'Hải Dương', 0971)
GO
INSERT INTO KHACHHANG(TenKH, NgaySinh, USERNAME, Email, DiaChi, DienThoai) VALUES (N'Anh','1/1/2022', 'kh3', 'anh@gmail.com', N'Hà Nam', 0971)
GO
INSERT INTO KHACHHANG(TenKH, NgaySinh, USERNAME, Email, DiaChi, DienThoai) VALUES (N'Sang', '1/1/2022', 'kh4', 'sang@gmail.com', N'Hải Phòng', 0971)
GO
INSERT INTO KHACHHANG(TenKH, NgaySinh, USERNAME, Email, DiaChi, DienThoai) VALUES (N'Sơn', '1/1/2022', 'kh5', 'son@gmail.com', N'Quảng Ninh', 0971)
GO


--DONHANG
--SELECT * FROM DONHANG
INSERT INTO DONHANG(PhuongThucThanhToan, ThanhTien, ThanhToan, DiaChiGiaoHang, TinhTrangGiaoHang, NgayDat, NgayGiao, MaKH, GhiChu) VALUES
(N'Thanh toán khi nhận hàng', 160000, N'Chưa thanh toán', N'Nguyên Xá', N'Đang giao', '1/1/2022', '2/1/2022', 'KH001', N'Giao nhanh')
GO
INSERT INTO DONHANG(PhuongThucThanhToan, ThanhTien, ThanhToan, DiaChiGiaoHang, TinhTrangGiaoHang, NgayDat, NgayGiao, MaKH, GhiChu) VALUES
(N'Thanh toán qua thẻ ngân hàng', 200000, N'Đã thanh toán', N'Văn trì' , N'Đã giao', '1/1/2022', '2/1/2022', 'KH002', N'Giao nhanh')
GO
INSERT INTO DONHANG(PhuongThucThanhToan, ThanhTien, ThanhToan, DiaChiGiaoHang, TinhTrangGiaoHang, NgayDat, NgayGiao, MaKH, GhiChu) VALUES
(N'Thanh toán khi nhận hàng', 240000, N'Chưa thanh toán', N'Ngọa Long' , N'Giao thất bại', '1/1/2022', '2/1/2022', 'KH003', N'Khách hàng không nhận')
GO
INSERT INTO DONHANG(PhuongThucThanhToan, ThanhTien, ThanhToan, DiaChiGiaoHang, TinhTrangGiaoHang, NgayDat, NgayGiao, MaKH, GhiChu) VALUES
(N'Thanh toán khi nhận hàng', 160000, N'Chưa thanh toán', N'Tây Tựu' , N'Giao thất bại', '1/1/2022', '2/1/2022', 'KH004', N'Trả hàng')
GO
INSERT INTO DONHANG(PhuongThucThanhToan, ThanhTien, ThanhToan, DiaChiGiaoHang, TinhTrangGiaoHang, NgayDat, NgayGiao, MaKH, GhiChu) VALUES
(N'Thanh toán khi nhận hàng', 160000, N'Chưa thanh toán', N'Tu Hoàng' , N'Đã giao', '1/1/2022', '2/1/2022', 'KH005', N'Giao thành công')
GO

--GIOHANG
--SELECT * FROM GIOHANG
INSERT INTO GIOHANG (MaDH) VALUES (N'DH001')
GO
INSERT INTO GIOHANG (MaDH) VALUES (N'DH002')
GO
INSERT INTO GIOHANG (MaDH) VALUES (N'DH003')
GO
INSERT INTO GIOHANG (MaDH) VALUES (N'DH004')
GO
INSERT INTO GIOHANG (MaDH) VALUES (N'DH005')
GO


--CHITIETDONHANG
--SELECT * FROM CHITIETDONHANG
--SELECT * FROM DONHANG
--SELECT * FROM SANPHAM

INSERT INTO CHITIETDONHANG(MaGH, MaSP, SoLuong, DonGia) VALUES ('GH001','SP001',4 , 40000)
GO
INSERT INTO CHITIETDONHANG(MaGH, MaSP, SoLuong, DonGia) VALUES ('GH002','SP002',4 , 50000)
GO
INSERT INTO CHITIETDONHANG(MaGH, MaSP, SoLuong, DonGia) VALUES ('GH003','SP003',4 , 60000)
GO
INSERT INTO CHITIETDONHANG(MaGH, MaSP, SoLuong, DonGia) VALUES ('GH004','SP001',4 , 40000)
GO
INSERT INTO CHITIETDONHANG(MaGH, MaSP, SoLuong, DonGia) VALUES ('GH005','SP001',4 , 40000)
GO

--NHACNVIEN
--SELECT * FROM NHANVIEN
--SELECT * FROM TAIKHOAN WHERE PhanQuyen = N'Nhân viên'
INSERT INTO NHANVIEN(TenNV, NgaySinh, Username, Email, DiaChi, DienThoai, STK, Luong) VALUES (N'Vũ','1/1/2020','nv1' ,'vu@gmail.com', N'Hà Nội', 0123, '123', 500000)
GO
INSERT INTO NHANVIEN(TenNV, NgaySinh, Username, Email, DiaChi, DienThoai, STK, Luong) VALUES (N'Bùi','1/1/2020','nv1' ,'bui@gmail.com', N'Hà Nội', 0123, '123', 500000)
GO
INSERT INTO NHANVIEN(TenNV, NgaySinh, Username, Email, DiaChi, DienThoai, STK, Luong) VALUES (N'Nguyễn','1/1/2020','nv1' ,'nguyen@gmail.com', N'Hà Nội', 0123, '123', 500000)
GO
INSERT INTO NHANVIEN(TenNV, NgaySinh, Username, Email, DiaChi, DienThoai, STK, Luong) VALUES (N'Triệu','1/1/2020','nv1' ,'trieu@gmail.com', N'Hà Nội', 0123, '123', 500000)
GO
INSERT INTO NHANVIEN(TenNV, NgaySinh, Username, Email, DiaChi, DienThoai, STK, Luong) VALUES (N'Đỗ','1/1/2020','nv1' ,'do@gmail.com', N'Hà Nội', 0123, '123', 500000)
GO

